config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
             :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  get 'pages/about'

  root 'pages#about'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        devise :omniauthable, :omniauth_providers => [:google_oauth2]

  validates :name, presence: true, length: {maximum: 25}

  after_create :send_notification

  def send_notification
  	MyMailer.new_user(self).deliver

  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid).first

    if user
      return user
    else
      registered_user = User.where(:email => access_token.email).first
      if registered_user
          return registered_user
      else
          user = User.create(
          name: data["name"],
          provider: access_token.provider,
          email: data["email"],
          uid: access_token.uid,
          image: data["image"],
          password: Devise.friendly_token[0,20]
          )
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :remember_me) }
  	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email, :password, :remember_me) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def google_oauth2
        @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

        if @user.persisted?
            flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
            sign_in_and_redirect @user, :event => :authentication
        else
            session["devise.google_data"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase 
		"https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=40"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Code4Pro</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<%= render partial: "shared/header" %>		
		<%= render partial: "shared/message" %>
		
		<main>
			<div class="container">
				<%= yield %>		
			</div>
		</main>

		<%= render partial: "shared/footer" %>

	</body>

	<script>
		$(".button-collapse").sideNav();
		$(".dropdown-button").dropdown();
	</script>

</html>

app/views/pages/about.html.erb
<h3>About Me</h3>

<div class="card z-depth-3">
	<div class="card-content white-text">
		<div class="row">
		<div class="col m6">
			<a class="twitter-timeline" href="https://twitter.com/1K1NG_1" data-widget-id="697771382315343872">Tweets by @1K1NG_1</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

		</div>

		<div class="col m6">
			<div class="card-panel grey lighten-5 z-depth-1">
				<div class="row valign-wrapper">
					<div class="col m3">
						<%= image_tag "IMG_0533.jpg", class: "circle responsive-img" %>
				</div>

				<div class="col m9">
					<span class="black-text">
						I don't know what to say. Let the world tell you more....:)
						</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
	<% resource.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>
	</script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer blue lighten-4">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Code4Pro</h5>
        <p class="grey-text text-lighten-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus ea sequi optio tempore, sint dolores eum quaerat ab? Quam animi, possimus quo harum, eius nihil similique. Possimus eos dolorum dicta!</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Social</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Google Plus</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2015 Copyright Code4Pro
    <%= link_to "About Us", pages_about_path, :class => "grey-text text-lighten-4 right" %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
	<!-- Dropdown Structure -->
	<ul id="dropdown1" class="dropdown-content">
	  <li><%= link_to "My Profile", edit_user_registration_path %></li>
	  <li><a href="#!">My Courses</a></li>
	  <li class="divider"></li>
	  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	</ul>

	<ul id="dropdown2" class="dropdown-content">
	  <li><%= link_to "My Profile", edit_user_registration_path %></li>
	  <li><a href="#!">My Courses</a></li>
	  <li class="divider"></li>
	  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	</ul>

	<nav class="blue lighten-4 z-depth-2">
		<div class="container">
	    <div class="nav-wrapper">
	      <a href="#!" class="brand-logo">Code4Pro</a>
	      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
	      <ul class="right hide-on-med-and-down">
	        <li><a href="#">Courses</a></li>
	        <% if(!user_signed_in?) %>
		        <li><%= link_to "Sign Up", new_user_registration_path %></li>
		        <li><%= link_to "Login", new_user_session_path %></li>
		      <% else%>
		        <!-- Dropdown Trigger -->
			      <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
			      	<%= image_tag avatar_url(current_user), class: "circle responsive-img" %>&nbsp;
			      	<%= current_user.name %><i class="mdi-navigation-arrow-drop-down right"></i></a>
			      </li>
		      <% end %>
	        
	      </ul>
	      <ul class="side-nav" id="mobile-demo">
	        <li><a href="#">Courses</a></li>
	        <% if(!user_signed_in?) %>
		        <li><%= link_to "Sign Up", new_user_registration_path %></li>
		        <li><%= link_to "Login", new_user_session_path %></li>
		      <% else%>
		        <!-- Dropdown Trigger -->
			      <li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
				      <%= image_tag avatar_url(current_user), class: "circle responsive-img" %>&nbsp;
				      <%= current_user.name %><i class="mdi-navigation-arrow-drop-down right"></i></a>
				    </li>
		      <% end %>
	      </ul>
	    </div>
    </div>
  </nav>
</header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
	<% flash.each do |f| %>
	<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		toastr['<%= type %>']('<%= f[1] %>')
	<% end %>
	</script>
<% end %>